export const GRID = {
  tileSize: 4.8,
  startRadius: 2,
  maxRadius: 7,
};

export const CARD_DEFS = {
  field: {
    category: 'ФЕРМА',
    name: 'Поле',
    icon: 'wheat',
    cost: {},
    tone: 'gold',
    description: 'Добавить часть поля. Вся связная группа растёт от 1 до 4 стадии; четыре части образуют комбо.',
  },
  pier: {
    category: 'МОРЕ',
    name: 'Причал',
    icon: 'anchor',
    cost: { wood: 3 },
    tone: 'blue',
    description: 'Ставится на воду у берега. Открывается через развитие деревообработки и запускает морскую ветку.',
  },
  island: {
    category: 'ЛАНДШАФТ',
    name: 'Расширение территории',
    icon: 'waves',
    cost: {},
    tone: 'green',
    description: 'Бесплатный фрагмент острова заданной формы. На карте заранее видно лес и камни; перед установкой фрагмент можно вращать Q/E.',
  },
  lighthouse: {
    category: 'НАВИГАЦИЯ',
    name: 'Маяк',
    icon: 'scan-line',
    cost: {},
    tone: 'gold',
    description: 'Особая карта морской экспедиции. Ставится на сушу или создаёт собственный остров вдали.',
  },
  fishingShop: {
    category: 'ПОРТ',
    name: 'Рыболовный магазин',
    icon: 'fish',
    cost: { wood: 2 },
    tone: 'blue',
    description: 'Открывается после выхода к морю. Получает карты за соседние причалы и жилые дома.',
  },
  tree: {
    category: 'ПРИРОДА',
    name: 'Посадить лес',
    icon: 'tree-pine',
    cost: {},
    tone: 'green',
    description: 'Базовая карта мира. Лесопилка даёт древесину за 1-ю обработку и вырубает дерево за 2-ю.',
  },
  rock: {
    category: 'ПРИРОДА',
    name: 'Камни',
    icon: 'mountain',
    cost: {},
    tone: 'stone',
    description: 'Базовая карта мира. Каменоломня даёт камень за 1-ю обработку и истощает залежь за 2-ю.',
  },
  clear: {
    category: 'ИНСТРУМЕНТ',
    name: 'Расчистка',
    icon: 'axe',
    cost: { wood: 1 },
    tone: 'red',
    description: 'Открывается после запуска первого производства. Убирает дерево или камень и освобождает клетку.',
  },
  mill: {
    category: 'ПОСТРОЙКА',
    name: 'Мельница',
    icon: 'wind',
    cost: { wood: 4, stone: 3 },
    tone: 'blue',
    description: 'Открывается первым комбо из 4 полей. Сначала строит мельницу, затем запускает большой урожай.',
  },
  house: {
    category: 'ПОСЕЛЕНИЕ',
    name: 'Дом',
    icon: 'house',
    cost: { wood: 2 },
    tone: 'blue',
    description: 'Базовая карта развития. Жилой дом усиливает рынок, построенный рядом.',
  },
  market: {
    category: 'ТОРГОВЛЯ',
    name: 'Рынок',
    icon: 'store',
    cost: { wood: 2, stone: 2 },
    tone: 'gold',
    description: 'Открывается первым связным комбо из 6 домов. Даёт больше очков за соседние дома.',
  },
  lumbermill: {
    category: 'ПРОИЗВОДСТВО',
    name: 'Лесопилка',
    icon: 'trees',
    cost: {},
    tone: 'green',
    description: 'Базовая карта развития. Обрабатывает соседний лес; повторная обработка завершает вырубку.',
  },
  quarry: {
    category: 'ПРОИЗВОДСТВО',
    name: 'Каменоломня',
    icon: 'pickaxe',
    cost: {},
    tone: 'stone',
    description: 'Базовая карта развития. Обрабатывает соседние камни; повторная обработка завершает добычу.',
  },
};

// main.js consumes this shared channel. card-progression-runtime.js installs
// live getters, so no fixed global probability table remains here.
export const DECK_WEIGHTS = [
  ['field',0],
  ['island',0],
  ['tree',0],
  ['rock',0],
  ['clear',0],
  ['house',0],
  ['market',0],
  ['pier',0],
  ['fishingShop',0],
  ['lumbermill',0],
  ['quarry',0],
];

export const DIRECTIONS = [
  { key: 'north', dx: 0, dz: -1 },
  { key: 'east', dx: 1, dz: 0 },
  { key: 'south', dx: 0, dz: 1 },
  { key: 'west', dx: -1, dz: 0 },
];
